def generate_answer_with_cortex(session, natural_query: str, table_name: str):
    # Sanitize inputs
    natural_query = natural_query.replace("`", "").replace("$$", "")
    table_name = table_name.replace("`", "").replace("$$", "")

    # Step 1: Generate SQL query
    sql_prompt = f"""
    You are an expert SQL generator for Snowflake. Given a question and table name, output a valid SQL query only. Do not include backticks, comments, or explanations.

    Table name: {table_name}
    Question: {natural_query}

    Output only the SQL query.
    """
    sql_gen_query = f"""
        SELECT SNOWFLAKE.CORTEX.COMPLETE(
            'mistral-large2',
            $$ {sql_prompt} $$
        ) AS result;
    """
    try:
        sql_result = session.sql(sql_gen_query).collect()
        generated_sql = sql_result[0]["RESULT"].strip().strip(";").strip("`")
        if not generated_sql.upper().startswith("SELECT"):
            raise ValueError("Invalid SQL query generated by Cortex")
    except Exception as e:
        print(f"Error generating SQL: {e}")
        raise

    # Step 2: Execute the SQL query
    try:
        result_df = session.sql(generated_sql).to_pandas()
    except Exception as e:
        print(f"SQL Execution Error: {e}")
        print(f"Generated SQL: {generated_sql}")
        raise

    # Step 3: Generate human-readable explanation
    summary_prompt = f"""
    You are an AI assistant. Given the user's question and the result of an SQL query in CSV format, respond in clear, simple English.

    Question: {natural_query}
    Table Result:
    {result_df.to_csv(index=False)}

    Provide a plain English summary of the results.
    """
    summary_query = f"""
        SELECT SNOWFLAKE.CORTEX.COMPLETE(
            'mistral-large2',
            $$ {summary_prompt} $$
        ) AS result;
    """
    try:
        summary_result = session.sql(summary_query).collect()
        human_answer = summary_result[0]["RESULT"]
    except Exception as e:
        print(f"Error generating summary: {e}")
        raise

    return {
        "sql": generated_sql,
        "answer": human_answer,
        "data": result_df
    }